services:
  # Data services
  pethaven-postgres:
    image: "postgres:16"
    container_name: pethaven.postgres
    restart: always
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
    volumes:
      - ./postgresql/init.sql:/docker-entrypoint-initdb.d/init.sql

